cmake_minimum_required(VERSION 3.0)

project(ComputerGraphicsStudies)

if(WIN32)
    set(CGS_WINDOWS TRUE)
    set(CGS_LINUX FALSE)
    set(CMAKE_WIN32_EXECUTABLE true)
else()
    set(CGS_WINDOWS FALSE)
    set(CGS_LINUX TRUE)
endif()

if(CGS_WINDOWS)
    add_executable(ComputerGraphicsStudies Win32Main.cpp)
elseif(CGS_LINUX)
    add_executable(ComputerGraphicsStudies LinuxMain.cpp)
else()
    message(FATAL_ERROR "Unsupported platform")
endif()

if(CGS_WINDOWS)
    target_compile_definitions(ComputerGraphicsStudies PRIVATE CGS_WINDOWS)
elseif(CGS_LINUX)
    target_compile_definitions(ComputerGraphicsStudies PRIVATE CGS_LINUX)
endif()