[Initialization]
Name = Engine
VersionVariant = 0
VersionMajor = 0
VersionMinor = 1
VersionPatch = 0
[RHI]
; EnableDebugLayer = true
; PhysicalDevice = "NVIDIA GeForce RTX 3080"
[Display]
Width = 1920
Height = 1080
[Graphics]
FrameBufferCount = 3
RenderersPath = Assets/Renderers
RenderGraphFilePath = Assets/Renderers/RenderGraph.xml
ShadersPath = Assets/Shaders
RenderPipelinesPath = Assets/RenderPipelines